// 'forth' vocabulary threads are at index 0
#define	LINK	1
#define	ASLEEP	2
#define	NUM_USER	3
#define	TO_IN	4
#define	BASE	5
#define	BLK	6
#define	NUM_TIB	7
#define	TICK_TIB	8
#define	NUM_SOURCE	9
#define	TICK_SOURCE	10
#define	STATE	11
#define	DELIMITER	12
#define	XSP	13
#define	XRP	14
#define	XFP	15
#define	TORIGIN	16
#define	DP	17
#define	LIMIT	18
#define	RAMCT	19
#define	RAMTOKENS	20
#define	COMPBUF	21
#define	LOCALS	22
#define	SAVED_DP	23
#define	SAVED_LIMIT	24
#define	SPZERO	25
#define	RPZERO	26
#define	UPZERO	27
#define	RSSAVE	28
#define	RSMARK	29
#define	NUM_OUT	30
#define	NUM_LINE	31
#define	DPL	32
#define	WARNING	33
#define	CAPS	34
#define	ERRNO	35
#define	FNUMPLACES	36
#define	HANDLER	37
#define	VOC_LINK	38
#define	LASTP	39
#define	ACCEPT	40
#define	THISDEF	41
#define	COMPLEVEL	42
#define	NUMINS	43
#define	LOCNUM	44
#define	SYSPTR	45
#define	BOUNDARY	46
#define	LESSIP	47
#define	IPGREATER	48
#define	CNT	49
#define	TICK_DEBUG	50
#define	CURRENT	51
#define	CONTEXT	52
#define	NVOCS	16
#define	NEXT_VAR	68
